import "./globals.css";
import "@/assets/css/app.css";
import Layout from "@/components/layout";
import AppScroll from "@/provider/app-scrollToTop";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`dark `}>
      <body>
        <AppScroll>
          <Layout>{children}</Layout>
        </AppScroll>
      </body>
    </html>
  );
}
